!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  auto_exposure: true
  auto_gain: true
  auto_saturation: false
  auto_sharpness: false
  auto_shutter: false
  auto_white_balance: false
  brightness: 0.0
  enable_strobe1: false
  enable_strobe2: false
  enable_trigger: true
  enable_trigger_delay: false
  exposure: 1.35
  format7_color_coding: mono8
  format7_roi_height: 0
  format7_roi_width: 0
  format7_x_offset: 0
  format7_y_offset: 0
  frame_rate: 15.0
  gain: 0.0
  gamma: 1.0
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      auto_exposure: true
      auto_gain: true
      auto_saturation: false
      auto_sharpness: false
      auto_shutter: false
      auto_white_balance: false
      brightness: 0.0
      enable_strobe1: false
      enable_strobe2: false
      enable_trigger: true
      enable_trigger_delay: false
      exposure: 1.35
      format7_color_coding: mono8
      format7_roi_height: 0
      format7_roi_width: 0
      format7_x_offset: 0
      format7_y_offset: 0
      frame_rate: 15.0
      gain: 0.0
      gamma: 1.0
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      id: 0
      name: Default
      pan: 0
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      saturation: 0.0
      sharpness: 0.0
      shutter_speed: 0.00201416015625
      state: true
      strobe1_delay: 0.0
      strobe1_duration: 0.0
      strobe1_polarity: 0
      strobe2_delay: 0.0
      strobe2_duration: 0.0
      strobe2_polarity: 0
      tilt: 0
      trigger_delay: 0.0
      trigger_mode: mode0
      trigger_parameter: 0
      trigger_polarity: 0
      trigger_source: gpio0
      type: ''
      video_mode: format7_mode1
      white_balance_blue: 0
      white_balance_red: 0
    state: []
  pan: 0
  saturation: 0.0
  sharpness: 0.0
  shutter_speed: 0.00201416015625
  strobe1_delay: 0.0
  strobe1_duration: 0.0
  strobe1_polarity: 0
  strobe2_delay: 0.0
  strobe2_duration: 0.0
  strobe2_polarity: 0
  tilt: 0
  trigger_delay: 0.0
  trigger_mode: mode0
  trigger_parameter: 0
  trigger_polarity: 0
  trigger_source: gpio0
  video_mode: format7_mode1
  white_balance_blue: 0
  white_balance_red: 0
state: []
